#!/bin/bash

URLS=$(tmux capture-pane -J -p | grep -oE '(https?):\/\/.*[^>]')

if [[ ! -z $URLS ]]; then
    tmux capture-pane -J -p | grep -oE '(https?):\/\/.*[^>]' | fzf-tmux -d20 --multi --bind alt-a:select-all,alt-d:deselect-all | xargs open
else
    echo "No URLs on this TMUX window"
fi
