#!/bin/bash

FILE=$1

if [[ -d $FILE ]]; then
    eza --git -alb --icons --classify "$FILE"
elif [[ $(file --mime "$FILE") =~ binary ]]; then
    printf '%s\nIs a binary FILE' "$FILE" && false
else
    bat --style=numbers --color=always "$FILE" 2>/dev/null | head -100
fi
