#!/bin/bash
if [ -z "$1" ]; then
    read -p "Enter your Git Username: " NAME
else
    NAME=$1
fi
if [ -z "$2" ]; then
    read -p "Enter your Git Email: " EMAIL
else
    EMAIL=$2
fi
if [ -z "$3" ]; then
    read -p "Enter your SSH Key Path: " KEY_PATH
    if [ -z "$KEY_PATH" ]; then
        echo "No SSH Key Path provided."
    else
        git config --local core.sshCommand "ssh -i $KEY_PATH"
    fi
else
    git config --local core.sshCommand "ssh -i $3"
fi
if [ -z "$4" ]; then
    read -p "Enter your GPG Key ID: " GPG_KEY
    if [ -z "$GPG_KEY" ]; then
        echo "No GPG Key ID provided."
    else
        git config --local user.signingkey "$GPG_KEY"
        git config --local commit.gpgsign true
    fi
else
    git config --local user.signingkey "$GPG_KEY"
    git config --local commit.gpgsign true
fi

git config --local user.name "$NAME"
git config --local user.email "$EMAIL"

git config --local -l
