
[debug]
log_level = "Off"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font" }

[terminal.shell]
program = "/opt/homebrew/bin/bash"
args = ["-l", "-c", "tmux attach || tmux new-session -s $USER"]

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 1, y = 0 }

