[debug]
log_level = "Off"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font" }

[shell]
program = "/usr/local/bin/fish"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 1, y = 0 }

# gruvbox-dark colorscheme
[colors.primary]
# hard contrast background = '#1d2021'
background = '#282828'
# soft contrast background = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'

# # Dracula scheme
# [colors.primary]
# background = "#282a36"
# foreground = "#f8f8f2"
# bright_foreground = "#ffffff"

# [colors.cursor]
# text = "#282a36"
# cursor = "#f8f8f2"

# [colors.vi_mode_cursor]
# text = "CellBackground"
# cursor = "CellForeground"

# [colors.selection]
# text = "CellForeground"
# background = "#44475a"

# [colors.normal]
# black = "#21222c"
# red = "#ff5555"
# green = "#50fa7b"
# yellow = "#f1fa8c"
# blue = "#bd93f9"
# magenta = "#ff79c6"
# cyan = "#8be9fd"
# white = "#f8f8f2"

# [colors.bright]
# black = "#6272a4"
# red = "#ff6e6e"
# green = "#69ff94"
# yellow = "#ffffa5"
# blue = "#d6acff"
# magenta = "#ff92df"
# cyan = "#a4ffff"
# white = "#ffffff"

# [colors.search.matches]
# foreground = "#44475a"
# background = "#50fa7b"

# [colors.search.focused_match]
# foreground = "#44475a"
# background = "#ffb86c"

# [colors.footer_bar]
# background = "#282a36"
# foreground = "#f8f8f2"

# [colors.hints.start]
# foreground = "#282a36"
# background = "#f1fa8c"

# [colors.hints.end]
# foreground = "#f1fa8c"
# background = "#282a36"
