import = ["~/.config/alacritty/gruvbox-dark.toml"]

[debug]
log_level = "Off"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font" }

[shell]
program = "bash"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 1, y = 0 }

# gruvbox-dark colorscheme
# Colors (Gruvbox dark)

# Default colors
[colors.primary]
# hard contrast background = = '#1d2021'
background = '#282828'
# soft contrast background = = '#32302f'
foreground = '#ebdbb2'

# Normal colors
[colors.normal]
black   = '#282828'
red     = '#cc241d'
green   = '#98971a'
yellow  = '#d79921'
blue    = '#458588'
magenta = '#b16286'
cyan    = '#689d6a'
white   = '#a89984'

# Bright colors
[colors.bright]
black   = '#928374'
red     = '#fb4934'
green   = '#b8bb26'
yellow  = '#fabd2f'
blue    = '#83a598'
magenta = '#d3869b'
cyan    = '#8ec07c'
white   = '#ebdbb2'


# [colors.bright]
# black = "#928374"
# blue = "#7daea3"
# cyan = "#89b482"
# green = "#a9b665"
# magenta = "#d3869b"
# red = "#ea6962"
# white = "#dfbf8e"
# yellow = "#e3a84e"
#
# [colors.normal]
# black = "#665c54"
# blue = "#7daea3"
# cyan = "#89b482"
# green = "#a9b665"
# magenta = "#d3869b"
# red = "#ea6962"
# white = "#dfbf8e"
# yellow = "#e78a4e"
#
# [colors.primary]
# background = "#282828"
# foreground = "#dfbf8e"
#
