set autoindent      
set background=dark 
set backspace=2     
set cursorcolumn
set cursorline
set expandtab       
set formatoptions=c,q,r,t 
set history=1000
set hlsearch        
set ignorecase      
set incsearch       
set mouse=a         
set nobackup
set nocompatible
set nowrap
set number          
set relativenumber
set ruler           
set scrolloff=10
set shiftwidth=4    
set showcmd         
set showmatch       
set showmode
set smartcase       
set smarttab        
set tabstop=4       
set textwidth=79    
set wildignore=*.docx,*.jpg,*.png,*.gif,*.pdf,*.pyc,*.exe,*.flv,*.img,*.xlsx
set wildmenu
set wildmode=list:longest
syntax on

filetype plugin indent on
filetype on

syntax on
syntax enable

if v:version < 802
    packadd! dracula
endif
set background=dark
colorscheme dracula

" VIMSCRIPT -------------------------------------------------------------- {{{

" This will enable code folding.
" Use the marker method of folding.
augroup filetype_vim
    autocmd!
    autocmd FileType vim setlocal foldmethod=marker
augroup END

" }}}
