// telemetry
user_pref("security.app_menu.recordEventTelemetry",                                    false);
user_pref("security.certerrors.recordEventTelemetry",                                  false);
user_pref("security.identitypopup.recordEventTelemetry",                               false);
user_pref("security.protectionspopup.recordEventTelemetry",                            false);
user_pref("network.trr.confirmation_telemetry_enabled",                                false);
user_pref("dom.security.unexpected_system_load_telemetry_enabled",                     false);
user_pref("browser.ping-centre.telemetry",                                             false);
user_pref("browser.newtabpage.activity-stream.feeds.telemetry",                        false);
user_pref("browser.newtabpage.activity-stream.telemetry.structuredIngestion.endpoint", "none");
user_pref("toolkit.telemetry.archive.enabled",                                         false);
user_pref("toolkit.telemetry.bhrPing.enabled",                                         false);
user_pref("toolkit.telemetry.dap_helper",                                              "none");
user_pref("toolkit.telemetry.dap_helper_owner",                                        "none");
user_pref("toolkit.telemetry.dap_leader",                                              "none");
user_pref("toolkit.telemetry.firstShutdownPing.enabled",                               false);
user_pref("toolkit.telemetry.newProfilePing.enabled",                                  false);
user_pref("toolkit.telemetry.pioneer-new-studies-available",                           false);
user_pref("toolkit.telemetry.reportingpolicy.firstRun",                                false);
user_pref("toolkit.telemetry.server",                                                  "none");
user_pref("toolkit.telemetry.server_owner",                                            "none");
user_pref("toolkit.telemetry.shutdownPingSender.enabled",                              false);
user_pref("toolkit.telemetry.unified",                                                 false);
user_pref("toolkit.telemetry.updatePing.enabled",                                      false);

// data reporting
user_pref("datareporting.healthreport.uploadEnabled",                                  false);
user_pref("datareporting.policy.dataSubmissionEnabled",                                false);

// other
user_pref("devtools.cache.disabled",                                                   true);
user_pref("accessibility.force_disabled",                                              1);
user_pref("browser.discovery.enabled",                                                 false);
user_pref("media.ffmpeg.vaapi.enabled",                                                true);
user_pref("network.captive-portal-service.enabled",                                    false);
user_pref("extensions.pocket.enabled",                                                 false);
user_pref("findbar.highlightAll",                                                      true);
user_pref("geo.enabled",                                                               false);
user_pref("widget.use-xdg-desktop-portal.settings",                                    0);
