[keyboard]
bindings = [
  { action = "Paste", key = "V", mods = "Command" },
  { chars = "^u", key = "u", mods = "Command" },
  { action = "Copy", key = "C", mods = "Command" },
  { action = "Quit", key = "Q", mods = "Command" },
  { action = "ToggleFullscreen", key = "Return", mods = "Command" },
  { action = "IncreaseFontSize", key = "Equals", mods = "Command" },
  { action = "DecreaseFontSize", key = "Minus", mods = "Command" },
  { action = "ResetFontSize", key = "Minus", mods = "Command|Shift" },
  { chars = "\u001B[1;2D", key = "Left", mods = "Shift" },
  { chars = "\u001B[1;5D", key = "Left", mods = "Control" },
  { chars = "\u001B[1;3D", key = "Left", mods = "Alt" },
  { chars = "\u001B[D", key = "Left", mode = "~AppCursor" },
  { chars = "\u001BOD", key = "Left", mode = "AppCursor" },
  { chars = "\u001B[1;2C", key = "Right", mods = "Shift" },
  { chars = "\u001B[1;5C", key = "Right", mods = "Control" },
  { chars = "\u001B[1;3C", key = "Right", mods = "Alt" },
  { chars = "\u001B[C", key = "Right", mode = "~AppCursor" },
  { chars = "\u001BOC", key = "Right", mode = "AppCursor" },
  { chars = "\u001B[1;2A", key = "Up", mods = "Shift" },
  { chars = "\u001B[1;5A", key = "Up", mods = "Control" },
  { chars = "\u001B[1;3A", key = "Up", mods = "Alt" },
  { chars = "\u001B[A", key = "Up", mode = "~AppCursor" },
  { chars = "\u001BOA", key = "Up", mode = "AppCursor" },
  { chars = "\u001B[1;2B", key = "Down", mods = "Shift" },
  { chars = "\u001B[1;5B", key = "Down", mods = "Control" },
  { chars = "\u001B[1;3B", key = "Down", mods = "Alt" },
  { chars = "\u001B[B", key = "Down", mode = "~AppCursor" },
  { chars = "\u001BOB", key = "Down", mode = "AppCursor" },
  { chars = "\u001B[Z", key = "Tab", mods = "Shift" },
  { chars = "\u001BOP", key = "F1" },
  { chars = "\u001BOQ", key = "F2" },
  { chars = "\u001BOR", key = "F3" },
  { chars = "\u001BOS", key = "F4" },
  { chars = "\u001B[15~", key = "F5" },
  { chars = "\u001B[17~", key = "F6" },
  { chars = "\u001B[18~", key = "F7" },
  { chars = "\u001B[19~", key = "F8" },
  { chars = "\u001B[20~", key = "F9" },
  { chars = "\u001B[21~", key = "F10" },
  { chars = "\u001B[23~", key = "F11" },
  { chars = "\u001B[24~", key = "F12" },
  { chars = "\u007F", key = "Back" },
  { chars = "\u001B\u007F", key = "Back", mods = "Alt" },
  { chars = "\u001B[2~", key = "Insert" },
  { chars = "\u001B[3~", key = "Delete" },
]
