[[keyboard.bindings]]
chars = "\u0002\""
key = "E"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002%"
key = "E"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B[A"
key = "Up"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[B"
key = "Down"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[C"
key = "Right"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B[D"
key = "Left"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002\u001B\u001B[A"
key = "Up"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B\u001B[B"
key = "Down"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B\u001B[C"
key = "Right"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002\u001B\u001B[D"
key = "Left"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
lk
"""
key = "F"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002[/"
key = "F"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = """
gitui
"""
key = "G"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002s"
key = "K"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002L"
key = "L"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002r"
key = "R"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002c"
key = "T"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002x"
key = "W"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002z"
key = "Z"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002n"
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0002,"
key = "Comma"
mods = "Command"

[[keyboard.bindings]]
chars = "\u0002p"
key = "{"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002n"
key = "}"
mods = "Command|Shift"

[[keyboard.bindings]]
chars = "\u0002:"
key = "Semicolon"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00021"
key = "Key1"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00022"
key = "Key2"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00023"
key = "Key3"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00024"
key = "Key4"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00025"
key = "Key5"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00026"
key = "Key6"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00027"
key = "Key7"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00028"
key = "Key8"
mods = "Command"

[[keyboard.bindings]]
chars = "\u00029"
key = "Key9"
mods = "Command"
