update_check = false
keymap_mode = "vim-insert"
ignored_commands = [ "ll","ls", ]
history_filter = [ "^ls$", "^ls -[a-zA-Z]*$", "^pwd$", "^clear$", "^exit$",
  "^history$", "^cd$", "^cd -$", "^cd \\.\\.$", "^cd ~$", ]
[sync]
records = true
