import = ["~/.config/alacritty/themes/gruvbox_dark.toml"]

[debug]
log_level = "Off"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font" }

[shell]
# program = "/usr/local/bin/fish"
program = "/bin/zsh"
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 1, y = 0 }
