import = ["~/.config/alacritty/themes/dracula.toml"]

[debug]
log_level = "Off"

[font]
size = 17
normal = { family = "UbuntuMono Nerd Font" }


[shell]
# program = "/usr/local/bin/fish"
# program = "/opt/homebrew/bin/bash"
program = "/bin/bash"
# args = ["-l", "-c", "zellij attach ^_^ || zellij -s ^_^"]
args = ["-l", "-c", "tmux attach || tmux"]

[window]
decorations = "none"
startup_mode = "Maximized"
option_as_alt = "Both"
padding = { x = 1, y = 0 }

[keyboard]
bindings = [
  # unbind new window shortcut
  { chars = "", key = "N", mods = "Control" },

  # # tmux
  # { chars = "\u0002\"", key = "E", mods = "Command" },
  # { chars = "\u0002%", key = "E", mods = "Command|Shift" },
  # { chars = "\u0002\u001B[A", key = "Up", mods = "Command" },
  # { chars = "\u0002\u001B[B", key = "Down", mods = "Command" },
  # { chars = "\u0002\u001B[C", key = "Right", mods = "Command" },
  # { chars = "\u0002\u001B[D", key = "Left", mods = "Command" },
  # { chars = "\u0002\u001B\u001B[A", key = "Up", mods = "Command|Shift" },
  # { chars = "\u0002\u001B\u001B[B", key = "Down", mods = "Command|Shift" },
  # { chars = "\u0002\u001B\u001B[C", key = "Right", mods = "Command|Shift" },
  # { chars = "\u0002\u001B\u001B[D", key = "Left", mods = "Command|Shift" },
  # { chars = "\u0002[/", key = "F", mods = "Command|Shift" },
  # { chars = "\u0002s", key = "K", mods = "Command" },
  # { chars = "\u0002L", key = "L", mods = "Command" },
  # { chars = "\u0002r", key = "R", mods = "Command" },
  # { chars = "\u0002c", key = "T", mods = "Command" },
  # { chars = "\u0002x", key = "W", mods = "Command" },
  # { chars = "\u0002z", key = "Z", mods = "Command" },
  # { chars = "\u0002n", key = "Tab", mods = "Control" },
  # { chars = "\u0002,", key = "Comma", mods = "Command" },
  # { chars = "\u0002\u005B", key = "C", mods = "Command|Shift" },
  # { chars = "\u0002p", key = "{", mods = "Command|Shift" },
  # { chars = "\u0002n", key = "}", mods = "Command|Shift" },
  # { chars = "\u0002:", key = "Semicolon", mods = "Command" },
  # { chars = "\u00021", key = "Key1", mods = "Command" },
  # { chars = "\u00022", key = "Key2", mods = "Command" },
  # { chars = "\u00023", key = "Key3", mods = "Command" },
  # { chars = "\u00024", key = "Key4", mods = "Command" },
  # { chars = "\u00025", key = "Key5", mods = "Command" },
  # { chars = "\u00026", key = "Key6", mods = "Command" },
  # { chars = "\u00027", key = "Key7", mods = "Command" },
  # { chars = "\u00028", key = "Key8", mods = "Command" },
  # { chars = "\u00029", key = "Key9", mods = "Command" },

  # # helix
  # { chars = "\u0013", key = "S", mods = "Command" },
]
