import = [
  "~/.config/alacritty/themes/dracula.toml",
  "~/.config/alacritty/bindings/general.toml",
  "~/.config/alacritty/bindings/tmux.toml",
  "~/.config/alacritty/bindings/helix.toml",
  "~/.config/alacritty/font.toml",
]
live_config_reload = true

[bell]
animation = "EaseOutExpo"
color = "#282a36"
duration = 300

[colors]
draw_bold_text_with_bright_colors = false

[cursor]
unfocused_hollow = true
style = { blinking = "Always", shape = "Block"}

[debug]
log_level = "OFF"
persistent_logging = false
print_events = false
render_timer = false

[mouse]
hide_when_typing = true

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[hints.enabled]]
command = "open"                          # On macOS
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
# binding = { key = "U", mods = "Command" }
# regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

# [mouse.hints]
# modifiers = "Command"

# [mouse.double_click]
# threshold = 300
# [mouse.triple_click]
# threshold = 300

[scrolling]
multiplier = 3

[selection]
save_to_clipboard = true
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[shell]
args = ["-l", "-c", "tmux attach || tmux new -s tmux"]
program = "/usr/local/bin/fish"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 1
option_as_alt = "Both"
startup_mode = "Maximized"

[window.padding]
x = 1
y = 1
