theme = "gruvbox"
# theme = "dracula"

[editor]
bufferline = "multiple"
color-modes = true
completion-trigger-len = 1
cursorcolumn = true
cursorline = true
idle-timeout = 0
insert-final-newline = true
line-number = "relative"
popup-border = "all"
shell = ["bash", "-c"]
undercurl = true

[editor.statusline]
left = [
  "mode",
  "separator",
  "version-control",
  "separator",
  "diagnostics",
  "separator",
  "spinner",
]
center = ["file-absolute-path", "file-modification-indicator"]
right = [
  "read-only-indicator",
  "file-encoding",
  "file-type",
  "register",
  "selections",
  "file-line-ending",
  "file-encoding",
  "position",
  "position-percentage",
  "total-line-numbers",
]
separator = " "

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.whitespace]
render = "all"

### NORMAL mode
[keys.normal]
"space" = { q = ":q!", x = ":bc!", e = [
  ":new",
  ":insert-output ~/.config/helix/scripts/lf-pick",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  "goto_last_modified_file",
  ":buffer-close!",
  ":redraw",
  ":reload",
] }
"C-r" = ":reload"
"C-g" = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload",
]
"C-t" = [
  ":new",
  ":insert-output tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E bash",
  ":buffer-close!",
  ":redraw",
  ":reload",
]
D = "delete_char_backward"
F = ":format" # fast format
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

### SELECT mode
[keys.select]
"space" = { q = ":q!", x = ":bc!", e = [
  ":new",
  ":insert-output ~/.config/helix/scripts/lf-pick",
  "select_all",
  "split_selection_on_newline",
  "goto_file",
  "goto_last_modified_file",
  ":buffer-close!",
  ":redraw",
] }
"C-r" = ":reload"
"C-g" = [
  ":new",
  ":insert-output lazygit",
  ":buffer-close!",
  ":redraw",
  ":reload",
]
"C-t" = [
  ":new",
  ":insert-output tmux popup -d \"#{pane_current_path}\" -xC -yC -w80% -h80% -E bash",
  ":buffer-close!",
  ":redraw",
  ":reload",
]
D = "delete_char_backward"
F = ":format" # fast format
X = "extend_line_above"
