theme = "dyracula"

[editor]
bufferline = "multiple"
color-modes = true
cursorcolumn = true
cursorline = true
line-number = "relative"
shell = ["bash", "-c"]
idle-timeout = 0
completion-trigger-len = 1

[editor.statusline]
left = [
  "mode",
  "separator",
  "version-control",
  "separator",
  "diagnostics",
  "separator",
  "spinner",
]
center = ["file-name", "file-modification-indicator"]
right = [
  "file-encoding",
  "file-type",
  "register",
  "selections",
  "file-encoding",
  "position",
  "position-percentage",
  "total-line-numbers",
]
separator = " "

[editor.indent-guides]
render = true
skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.file-picker]
hidden = false
git-ignore = false
git-global = false

[editor.whitespace]
render = "all"

### NORMAL mode
[keys.normal]
q = { w = ":wq!", q = ":q!" } # fast exit
"space" = { W = ":w!", q = ":q!", c = ":bc!" }
C-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
] # move line down
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
] # move line up
C-s = ":w!" # fast saving
D = "delete_char_backward"
F = ":format" # fast format
G = "goto_last_line"
X = "extend_line_above"
esc = ["collapse_selection", "keep_primary_selection"]

### SELECT mode
[keys.select]
"space" = { W = ":w!", q = ":q!", c = ":bc!" }
C-j = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
] # move line down
C-k = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
] # move line up
C-s = ":w!" # fast saving
D = "delete_char_backward"
F = ":format" # fast format
G = "goto_last_line"
X = "extend_line_above"

### INSERT mode
[keys.insert]
j = { k = "normal_mode" }    # Maps `jk` to exit insert mode
C-s = ["normal_mode", ":w!"]
